echo "=== GUIDE SIMPLE POUR ELIMINER 'NOT SECURE' ==="
echo ""
echo "METHODE 1: Installation manuelle du certificat (RECOMMANDEE)"
echo ""
echo "1. Ouvrez l'Explorateur Windows"
echo "2. Allez dans: C:\xampp\apache\conf\ssl.crt\"
echo "3. Clic droit sur: smp_rsa_pq.crt"
echo "4. Choisissez: 'Installer le certificat'"
echo "5. Emplacement: 'Ordinateur local'"
echo "6. Magasin: 'Autorites de certification racines de confiance'"
echo "7. Validez l'installation"
echo "8. Redemarrez vos navigateurs"
echo "9. Testez: https://localhost/smp/"
echo ""
echo "METHODE 2: Flags navigateur (TEMPORAIRE)"
echo ""
echo "Chrome:"
echo "  - chrome://flags/#allow-insecure-localhost"
echo "  - Activez: 'Allow invalid certificates for resources loaded from localhost'"
echo ""
echo "Firefox:"
echo "  - about:config"
echo "  - security.tls.insecure_fallback_hosts = localhost"
echo ""
echo "METHODE 3: Ignorer l'avertissement (SIMPLE)"
echo ""
echo "1. Allez sur https://localhost/smp/"
echo "2. Cliquez 'Parametres avances'"
echo "3. Cliquez 'Continuer vers localhost (dangereux)'"
echo "4. Le navigateur se souviendra de votre choix"
echo ""
echo "RESULTAT: Plus d'avertissement 'Not secure'"

# Ouvrir le dossier des certificats
start "" "C:\xampp\apache\conf\ssl.crt\"